name: flondart
description: Armonia Meta Chain RPC API client in Dart language
version: 0.4.8+20220825
homepage: https://github.com/armoniax/flutter-sdk-flondart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.0
  json_annotation: ^4.0.1
  pointycastle: ^3.3.5
  flondart_ecc: ^0.4.4

dev_dependencies:
  test: ^1.19.2
  build_runner: ^2.1.4
  json_serializable: ^6.0.1
