name: flondart
description: FullOn Network RPC API client in Dart language
version: 0.4.8+20220825
homepage: https://github.com/fullon-labs/flondart
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^1.0.0
  json_annotation: ^4.9.0
  pointycastle: ^3.3.5
  common_utils: ^2.1.0
  get: ^4.6.6
  flondart_ecc:
    git: 
      url: https://github.com/fullon-labs/flondart-ecc.git
      ref: v1.0.0

dev_dependencies:
  test: ^1.19.2
  build_runner: ^2.1.4
  json_serializable: ^6.0.1
